name: Ticket Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:         # allow manual run from GitHub UI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Run ticket checker
        env:
          GMAIL_USER: ${{ vars.GMAIL_USER }}
          GMAIL_PASS: ${{ vars.GMAIL_PASS }}
        run: ruby ticket_checker.rb
